## Import Data and Modules

In [3]:
import pandas as pd

## read zip file

In [2]:
# Read zip file
df = pd.read_csv("Data/uszips.csv")
df.head()

,zip,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,county_fips,county_name,all_county_weights,imprecise,military,timezone
0,601,18.18004,-66.75218,Adjuntas,PR,Puerto Rico,True,NaN,18570,111.4,72001,Adjuntas,"{'72001':99.43,'72141':0.57}",False,False,America/Puerto_Rico
1,602,18.36073,-67.17517,Aguada,PR,Puerto Rico,True,NaN,41520,523.5,72003,Aguada,{'72003':100},False,False,America/Puerto_Rico
2,603,18.45439,-67.12202,Aguadilla,PR,Puerto Rico,True,NaN,54689,667.9,72005,Aguadilla,{'72005':100},False,False,America/Puerto_Rico
3,606,18.16724,-66.93828,Maricao,PR,Puerto Rico,True,NaN,6615,60.4,72093,Maricao,"{'72093':94.88,'72121':1.35,'72153':3.78}",False,False,America/Puerto_Rico
4,610,18.29032,-67.12243,Anasco,PR,Puerto Rico,True,NaN,29016,312.0,72011,Añasco,"{'72003':0.55,'72011':99.45}",False,False,America/Puerto_Rico

## Data Cleaning

### a) Drop Useless Columns

In [4]:
drop_columns_df = df.drop(columns=[
    "zcta", #not needed
    "parent_zcta", #not needed
    "county_fips", #not needed
    "all_county_weights", #not needed
    "imprecise", #not needed
    "military", #not needed
    "timezone", #not needed
])
drop_columns_df.head()

,zip,lat,lng,city,state_id,state_name,population,density,county_name
0,601,18.18004,-66.75218,Adjuntas,PR,Puerto Rico,18570,111.4,Adjuntas
1,602,18.36073,-67.17517,Aguada,PR,Puerto Rico,41520,523.5,Aguada
2,603,18.45439,-67.12202,Aguadilla,PR,Puerto Rico,54689,667.9,Aguadilla
3,606,18.16724,-66.93828,Maricao,PR,Puerto Rico,6615,60.4,Maricao
4,610,18.29032,-67.12243,Anasco,PR,Puerto Rico,29016,312.0,Añasco

### a) Drop Useless Columns

In [5]:
rename_columns_df = drop_columns_df.rename(columns={
    "lat":"zip_lat",
    "lng":"zip_lng"
})

rename_columns_df.head()

,zip,zip_lat,zip_lng,city,state_id,state_name,population,density,county_name
0,601,18.18004,-66.75218,Adjuntas,PR,Puerto Rico,18570,111.4,Adjuntas
1,602,18.36073,-67.17517,Aguada,PR,Puerto Rico,41520,523.5,Aguada
2,603,18.45439,-67.12202,Aguadilla,PR,Puerto Rico,54689,667.9,Aguadilla
3,606,18.16724,-66.93828,Maricao,PR,Puerto Rico,6615,60.4,Maricao
4,610,18.29032,-67.12243,Anasco,PR,Puerto Rico,29016,312.0,Añasco

## Export Clean Zip file

In [6]:
rename_columns_df.to_csv("Data/clean_zip.csv",index=False)